name: lazysinger

services:
  redis:
    container_name: redis
    env_file:
      - .env
    image: "redis:8.2.1"
    command: "redis-server --save 20 1 --loglevel warning"
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  asynqmon:
    image: hibiken/asynqmon
    environment:
      REDIS_ADDR: redis:6379
    ports:
      - 8080:8080
    depends_on:
      - redis

  studio:
    image: frectonz/sql-studio
    ports:
      - 3030:3030
    volumes:
      - ./data:/data
    command: /bin/sql-studio --no-browser --no-shutdown --address=0.0.0.0:3030 sqlite /data/lazysinger.db

volumes:
  redis_data:
