// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
)

type Track struct {
	ID              int64          `json:"id"`
	Path            string         `json:"path"`
	Title           sql.NullString `json:"title"`
	Artist          sql.NullString `json:"artist"`
	Album           sql.NullString `json:"album"`
	Duration        float64        `json:"duration"`
	HasPlainLyrics  bool           `json:"has_plain_lyrics"`
	HasSyncedLyrics bool           `json:"has_synced_lyrics"`
}
