// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
)

type Track struct {
	ID              int64
	Path            string
	Title           sql.NullString
	Artist          sql.NullString
	Album           sql.NullString
	Duration        float64
	HasPlainLyrics  bool
	HasSyncedLyrics bool
}
