// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracks.sql

package repository

import (
	"context"
	"database/sql"
)

const createTrack = `-- name: CreateTrack :exec
INSERT INTO tracks (
    path,
    title,
    artist,
    album,
    duration,
    has_plain_lyrics,
    has_synced_lyrics
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateTrackParams struct {
	Path            string
	Title           sql.NullString
	Artist          sql.NullString
	Album           sql.NullString
	Duration        float64
	HasPlainLyrics  bool
	HasSyncedLyrics bool
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) error {
	_, err := q.db.ExecContext(ctx, createTrack,
		arg.Path,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.Duration,
		arg.HasPlainLyrics,
		arg.HasSyncedLyrics,
	)
	return err
}

const deleteTrack = `-- name: DeleteTrack :exec
DELETE FROM tracks WHERE path = ?
`

func (q *Queries) DeleteTrack(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteTrack, path)
	return err
}

const getAllTracks = `-- name: GetAllTracks :many
SELECT id, path, title, artist, album, duration, has_plain_lyrics, has_synced_lyrics FROM tracks
`

func (q *Queries) GetAllTracks(ctx context.Context) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, getAllTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Duration,
			&i.HasPlainLyrics,
			&i.HasSyncedLyrics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrackByPath = `-- name: GetTrackByPath :one
SELECT id, path, title, artist, album, duration, has_plain_lyrics, has_synced_lyrics FROM tracks WHERE path = ? LIMIT 1
`

func (q *Queries) GetTrackByPath(ctx context.Context, path string) (Track, error) {
	row := q.db.QueryRowContext(ctx, getTrackByPath, path)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.Duration,
		&i.HasPlainLyrics,
		&i.HasSyncedLyrics,
	)
	return i, err
}

const getTracksByAlbum = `-- name: GetTracksByAlbum :many
SELECT id, path, title, artist, album, duration, has_plain_lyrics, has_synced_lyrics FROM tracks WHERE album = ? ORDER BY title
`

func (q *Queries) GetTracksByAlbum(ctx context.Context, album sql.NullString) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, getTracksByAlbum, album)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Duration,
			&i.HasPlainLyrics,
			&i.HasSyncedLyrics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTracksByArtist = `-- name: GetTracksByArtist :many
SELECT id, path, title, artist, album, duration, has_plain_lyrics, has_synced_lyrics FROM tracks WHERE artist = ? ORDER BY album, title
`

func (q *Queries) GetTracksByArtist(ctx context.Context, artist sql.NullString) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, getTracksByArtist, artist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Duration,
			&i.HasPlainLyrics,
			&i.HasSyncedLyrics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTracks = `-- name: SearchTracks :many
SELECT id, path, title, artist, album, duration, has_plain_lyrics, has_synced_lyrics FROM tracks
WHERE title LIKE ? OR artist LIKE ? OR album LIKE ?
ORDER BY artist, album, title
`

type SearchTracksParams struct {
	Title  sql.NullString
	Artist sql.NullString
	Album  sql.NullString
}

func (q *Queries) SearchTracks(ctx context.Context, arg SearchTracksParams) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, searchTracks, arg.Title, arg.Artist, arg.Album)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Duration,
			&i.HasPlainLyrics,
			&i.HasSyncedLyrics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrack = `-- name: UpdateTrack :exec
UPDATE tracks
SET
    title = ?,
    artist = ?,
    album = ?,
    duration = ?,
    has_plain_lyrics = ?,
    has_synced_lyrics = ?
WHERE path = ?
`

type UpdateTrackParams struct {
	Title           sql.NullString
	Artist          sql.NullString
	Album           sql.NullString
	Duration        float64
	HasPlainLyrics  bool
	HasSyncedLyrics bool
	Path            string
}

func (q *Queries) UpdateTrack(ctx context.Context, arg UpdateTrackParams) error {
	_, err := q.db.ExecContext(ctx, updateTrack,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.Duration,
		arg.HasPlainLyrics,
		arg.HasSyncedLyrics,
		arg.Path,
	)
	return err
}
